[package]
name = "cw-snapshot-vector-map"
authors = ["noah <noah@daodao.zone>"]
description = "A CosmWasm vector that allows snapshotting values at a given height."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw20 = { workspace = true }
serde = { workspace = true }
